# Generated by Django 3.1.7 on 2021-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
