# Generated by Django 3.1.7 on 2021-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210520_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
